### ISSUE TITLE
Porting to Python 3

### ISSUE THREAD

**Issue by eugeneyan** [hermanschaaf/pythai#3]
Thank you very much for sharing this package! It's been very helpful in some tasks I undertake such as product classification and improves accuracy significantly. 

With the new year, I'm looking to port my work to Python 3--unfortunately, I'm unable to port `Py_InitModule` to its equivalent `PyModule_Create` (in `libthai.c`). Are there any plans to port pythai to Python 3?

**Comment by hermanschaaf** [comment]
Hi @eugeneyan I'm afraid I don't have such plans, but I would be happy to merge any pull requests that add Python 3 support (without breaking Python 2)!
